plugins {
    id 'java'
    id 'maven-publish'
}

group 'com.qahelpers'
version '2.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation(
            'org.apache.poi:poi-ooxml:5.5.1',
            'org.apache.poi:poi:5.5.1',
            'org.hamcrest:hamcrest:3.0'
    )

    testImplementation('org.junit.jupiter:junit-jupiter-api:6.1.2')
    testImplementation('org.hamcrest:hamcrest:3.0') { transitive = false }
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:6.1.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:6.1.2'
    testRuntimeOnly 'org.apache.logging.log4j:log4j-core:2.25.4'
}

test {
    useJUnitPlatform()
}
